develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35735:35729"
  container_name: gfw-user-api-develop
  environment:
    NODE_ENV: dev
    API_GATEWAY_URL: http://mymachine:8000
    MIGRATE_URI: <urlmigrate>
  command: develop
  links:
    - mongo
  volumes:
    - ./app:/opt/gfw-user-api/app
mongo:
  image: mongo
  container_name: gfw-user-mongo
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    - $HOME/docker/data/gfw-user-api:/data/db
  restart: always
