develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35731:35729"
  container_name: gfw-user-api-develop
  environment:
    NODE_ENV: dev
    API_GATEWAY_URI: http://192.168.99.100:8000/gateway/service
    SELF_REGISTRY: "true"
  command: develop
  links:
    - mongo
  volumes:
    - ./app:/opt/gfw-user-api/app
mongo:
  image: mongo
  container_name: gfw-user-mongo
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    # in osx the host machine volume directory cannot be under /Users
    # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
    - /var/docker/data/gfw-user-api:/data/db
  restart: always
