prod:
  image: vizzuality/gfw-user-api:1.0.3${STAGING}
  ports:
    - "3100"
  env_file:
    - prod.env
  command: start
  restart: always
  dns: ${DNS_SERVER}
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: gfw-user-api${STAGING}

